### ISSUE TITLE
Suggest topics that should be applied to repository - list of topics

### ISSUE THREAD

**Issue by filipowm** [Roche/the-ambassador#157]
It should be possible to provide a list of topics, that are preferred, together with it's synonyms / abbreviations.

Example configuration:
```yaml
ambassador:
  topics:
    preferred:
      - value: topicX
        synonyms:
          - tx
          - topic-x
          - fantasticTopic
```

Application must verify for any duplicates in whole set of topics -- values and synonyms, and fail as needed.
